#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — the manual half of the first real run.
#
# Everything a machine could do is already done: the Neon project exists, the
# migrations are applied, `.env` and `worker/.env` are written, and the two
# connection experiments have been run. What is left is the four things only a
# person can do, and this walks them in order.
#
# ⚠️ The console flow below is Google's **Google Auth Platform**, which replaced
# the old "OAuth consent screen" page. Checked against Google's own guide on
# 2026-09-12 (page last updated 2026-09-03); if the console has moved again,
# fix this file rather than improvising once.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
if [[ ! -f package.json || ! -d worker ]]; then
  printf 'Run this from the kioku repo.\n' >&2
  exit 1
fi

banner "Kioku — the first real run"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — a project to hang the OAuth client on"
say "Kioku signs one person in with Google (ADR 0017). That needs an OAuth"
say "client, and an OAuth client needs a Cloud project to live in."
say ""
open_url "https://console.cloud.google.com/projectcreate"
step "Name it 'kioku' (the name is only ever shown to you)."
step "Leave the organisation and location as offered."
step "Click Create, then wait for the project to become the selected one —"
step "  the picker at the top of the page should read 'kioku'."
say ""
say "If you already have a project you'd rather use, select it instead and"
say "skip the create — nothing below depends on the project being new."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Google Auth Platform — branding, and the audience of one"
say "This is the step whose omission produces 'Access blocked: kioku has not"
say "completed the Google verification process' at sign-in, which reads like a"
say "code problem and is not one."
say ""
open_url "https://console.cloud.google.com/auth/branding"
step "If you see 'Google Auth platform not configured yet', click Get Started."
step "App name: Kioku. User support email: your own address."
step "Audience: choose External. (Internal needs a Workspace organisation.)"
step "Contact information: your own address again."
step "Agree to the User Data Policy, Continue, Create."
say ""
open_url "https://console.cloud.google.com/auth/audience"
step "Under Test users, click Add users, and add the ONE address that"
step "  KIOKU_INVITED_EMAIL is set to. Save."
say ""
say "⚠️ Leave the publishing status on Testing. Kioku's allowlist is one email"
say "   (\`08\` §4) and Google's test-user list is a second, independent gate."
say "   Publishing the app would remove the outer one for no gain."
say ""
say "You do NOT need to touch Data Access. Better Auth asks for openid, email"
say "and profile; all three are non-sensitive and need no review."
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The OAuth client — and the one URI that must match exactly"
open_url "https://console.cloud.google.com/auth/clients"
step "Click Create client."
step "Application type: Web application."
step "Name: kioku-localhost."
say ""
say "Under 'Authorised redirect URIs' click Add URI and paste EXACTLY:"
say ""
say "    http://localhost:3000/api/auth/callback/google"
say ""
say "⚠️ Three things about that line, each of which fails as redirect_uri_mismatch:"
step "http, not https — Google exempts localhost from the HTTPS rule, and"
step "  BETTER_AUTH_URL is http, so https here would not match."
step "Port 3000 — it must equal the port \`npm run dev\` actually serves on."
step "No trailing slash, and the path is /api/auth/callback/google."
say ""
say "You do not need an 'Authorised JavaScript origin'. Better Auth's flow is a"
say "server-side redirect, not a browser-side token grant."
say ""
step "Click Create. A dialog shows the Client ID and Client secret."
ask GOOGLE_CLIENT_ID "Paste the Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Client secret (hidden):"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The Anthropic key — the worker's, and only the worker's"
say "The pipeline makes one model request per chunk. The key lives in"
say "worker/.env and never on the app tier: \`03\` §13.1 keeps the process with"
say "an internet-facing surface unable to spend money, and there is a test"
say "(test/unit/no-provider-key-in-the-app.test.ts) that fails if that slips."
say ""
open_url "https://console.anthropic.com/settings/keys"
step "Create Key, name it 'kioku-worker', copy it."
ENV_FILE="worker/.env"
ask_secret ANTHROPIC_API_KEY "Paste the Anthropic API key (hidden):"
write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Sign in — the first time anyone ever has"
say "Two values went into .env (GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET) and one"
say "into worker/.env (ANTHROPIC_API_KEY). The database, the migrations and"
say "every other variable are already in place."
say ""
say "In a terminal:"
say ""
say "    npm run dev"
say ""
step "Open http://localhost:3000 — you should be redirected to /auth."
step "Click the one button. Google will warn that the app is unverified;"
step "  that is the Testing status from stage 2 and is expected. Continue."
step "You should land signed in, not on /auth/refused."
say ""
say "If you land on /auth/refused, the allowlist refused you: the Google account"
say "you signed in with is not the address in KIOKU_INVITED_EMAIL. That is the"
say "gate working (\`08\` §3.1), not a bug."
say ""
say "⚠️ Then STOP and open docs/first-run-expectation.md before you paste any"
say "   Japanese. It asks for four numbers written down BEFORE the run. A"
say "   prediction recorded afterwards is not a prediction, and ADR 0037 makes"
say "   this run the instrument for S3 and S10."
pause

finish
